### ISSUE TITLE
希望加入工时统计

### ISSUE THREAD

**Issue by czxin788** [lanyulei/ferry#106]
期望加入工时统计功能，这样可以查看每个月每个员工都处理了多少工单，用了多少工时。考核员工工作量

**Comment by zy410692** [comment]
+员工审批节点的次数。

**Comment by charnet1019** [comment]
可以调用自定义webhook接口，主要想实现将上线发布参数传递给webhook，webhook接收到发布参数调用jenkins api实现自动发布逻辑

**Comment by kaylin123** [comment]
> 期望加入工时统计功能，这样可以查看每个月每个员工都处理了多少工单，用了多少工时。考核员工工作量

对，最好细化到哪一个环节的具体用时，那样对工作量的考虑有比较好参考意义。

另外，希望增加工单类别的统计，就能知道哪一类问题提的最多，从而根据重点改进能效。

**Comment by lanyulei** [comment]
已重构，有问题可继续提出。

**Comment by charnet1019** [comment]
> 可以调用自定义webhook接口，主要想实现将上线发布参数传递给webhook，webhook接收到发布参数调用jenkins api实现自动发布逻辑

@lanyulei  这个调用webhook的功能是否可以加上？

**Comment by chuchangyan** [comment]
@lanyulei 这个调用webhook的功能是否可以加上？

**Comment by lanyulei** [comment]
@charnet1019 @chuchangyan  可使用任务。
