### ISSUE TITLE
go run main.go init错误

### ISSUE THREAD

**Issue by CedrusZhao** [lanyulei/ferry#126]
**Describe the bug**
当我执行初始化命令时，`go run main.go init -c=config/settings.dev.yml`报如下错误：
exec: "C:\\Users\\asus\\AppData\\Local\\Temp\\go-build648857162\\b001\\exe\\main": file does not exist
我用的windows操作系统，我猜测是因为权限的问题，但是一时没有找到好的解决办法。

**Comment by lanyulei** [comment]
编译成二进制以后试试呢。

**Comment by CedrusZhao** [comment]
嗯嗯，谢谢。我使用goland编译运行成功啦
