### ISSUE TITLE
创建test用户，登录时产生无限请求

### ISSUE THREAD

**Issue by jiaxinonly** [lanyulei/ferry#150]
你好，我刚刚使用docker部署的ferry，在添加一个test用户后，尝试登录，结果发生了无限请求，需要重启容器才能恢复，这是否是一个BUG？
![image](https://user-images.githubusercontent.com/57223696/112433275-fae98080-8d7c-11eb-85c3-08a805a535e4.png)
![image](https://user-images.githubusercontent.com/57223696/112433375-1b193f80-8d7d-11eb-9721-af4269e7449b.png)

**Comment by lanyulei** [comment]
已修复。

**Comment by jiaxinonly** [comment]
请问这是如何引起的？该怎么避免？因为我是使用docker部署的，docker好像还没有更新，这个bug依然存在
