### ISSUE TITLE
用户需要开放修改管理员权限，才能修改自己信息

### ISSUE THREAD

**Issue by jiaxinonly** [lanyulei/ferry#153]
你好，使用LADP导入用户后，用户登录修改自己的手机号，提示没有权限
![image](https://user-images.githubusercontent.com/57223696/112794127-00a2d700-9099-11eb-9b06-70a547b318ae.png)
需要开放修改管理员权限才能正常使用，这应该是一个bug吧？
![image](https://user-images.githubusercontent.com/57223696/112793877-a0139a00-9098-11eb-9761-867f294e231a.png)

**Comment by lanyulei** [comment]
没问题啊，你如果要修改信息，开通权限即可。

**Comment by jiaxinonly** [comment]
那请问这样，普通用户是不是可以调用接口修改别人的用户信息？甚至是管理员的？
