### ISSUE TITLE
工单模板信息里面的多选框条目显示不正确

### ISSUE THREAD

**Issue by flybird119** [lanyulei/ferry#154]
新建模板，正常添加加3个多选框（centos、windows、ubuntu），工单流转过程中使用该模板，但在工单的历史信息里面，这3个多选框显示不正确，变成了：[ "Option 1", "Option 2", "centos" ]
![image](https://user-images.githubusercontent.com/10595211/112921255-03ef9e80-913d-11eb-98dd-0a0fb98ed5cc.png)
![image](https://user-images.githubusercontent.com/10595211/112921368-3c8f7800-913d-11eb-8da9-e2a0da30de81.png)

**Comment by lanyulei** [comment]
![image](https://user-images.githubusercontent.com/20027531/113314179-9d39d300-933e-11eb-9a90-c3003f648880.png)
我这边测试没问题呢。
