### ISSUE TITLE
流程必选选项不选中可以提交

### ISSUE THREAD

**Issue by liuhaixiao** [lanyulei/ferry#194]
1.制定了模板 模板用于第二个节点流程中，第二个流程中 模板可以编辑 可以选择 ，但是必选项不生效  不选择必选项可以直接提交。

**Comment by lanyulei** [comment]
我这边测试没有问题呢，方便具体描述下吗？
![image](https://user-images.githubusercontent.com/20027531/120583205-58c2d480-c460-11eb-8963-41c027104c03.png)
