### ISSUE TITLE
docker方式部署，提交工单报错“新建历史记录失败，Error 1054: Unknown column 'status' in 'field list'”

### ISSUE THREAD

**Issue by gander001** [lanyulei/ferry#195]
按照 https://www.fdevops.com/docs/ferry-tutorial-document/docker-ferry-install 部署

1：登录之后，首页报错：
查询处理工单人员排行失败

2：提交工单
“新建历史记录失败，Error 1054: Unknown column 'status' in 'field list'”

docker logs 查看的 ferry_backend 部分日志
{"level":"info","ts":"2021-05-26 17:47:12.869738","caller":"middleware/permission.go:24","msg":"admin/api/v1/work-order/createPOST"}
{"level":"error","ts":"2021-05-26 17:47:12.944776","caller":"app/return.go:17","msg":"新建历史记录失败，Error 1054: Unknown column 'status' in 'field list'"}
{"level":"info","ts":"2021-05-26 17:47:12.944856","caller":"middleware/logger.go:39","msg":" 2021-05-26 17:47:12.863 200   81.749528ms   172.21.101.17 POST /api/v1/work-order/create"}
{"level":"info","ts":"2021-05-26 17:48:27.522547","caller":"middleware/permission.go:24","msg":"admin/api/v1/work-order/createPOST"}
{"level":"error","ts":"2021-05-26 17:48:27.794427","caller":"app/return.go:17","msg":"新建历史记录失败，Error 1054: Unknown column 'status' in 'field list'"}
{"level":"info","ts":"2021-05-26 17:48:27.794514","caller":"middleware/logger.go:39","msg":" 2021-05-26 17:48:27.5108 200  283.634086ms   172.21.101.17 POST /api/v1/work-order/create"}
{"level":"info","ts":"2021-05-26 17:49:32.924979","caller":"middleware/permission.go:24","msg":"admin/api/v1/process/classifyGET"}
{"level":"info","ts":"2021-05-26 17:49:32.928551","caller":"middleware/logger.go:39","msg":" 2021-05-26 17:49:32.9185 200   10.017936ms   172.21.101.17 GET /api/v1/process/classify"}
{"level":"info","ts":"2021-05-26 17:49:35.357721","caller":"middleware/permission.go:24","msg":"admin/api/v1/work-order/process-structureGET"}
{"level":"info","ts":"2021-05-26 17:49:35.363202","caller":"middleware/logger.go:39","msg":" 2021-05-26 17:49:35.3512 200   11.908274ms   172.21.101.17 GET /api/v1/work-order/process-structure?processId=1"}
{"level":"info","ts":"2021-05-26 17:49:39.860364","caller":"middleware/permission.go:24","msg":"admin/api/v1/work-order/createPOST"}
{"level":"error","ts":"2021-05-26 17:49:39.957966","caller":"app/return.go:17","msg":"新建历史记录失败，Error 1054: Unknown column 'status' in 'field list'"}
{"level":"info","ts":"2021-05-26 17:49:39.958070","caller":"middleware/logger.go:39","msg":" 2021-05-26 17:49:39.8502 200  107.767775ms   172.21.101.17 POST /api/v1/work-order/create"}
{"level":"info","ts":"2021-05-26 17:52:04.704914","caller":"middleware/permission.go:24","msg":"admin/api/v1/dashboardGET"}
{"level":"error","ts":"2021-05-26 17:52:04.721741","caller":"app/return.go:17","msg":"查询处理工单人员排行失败"}
{"level":"info","ts":"2021-05-26 17:52:04.721803","caller":"middleware/logger.go:39","msg":" 2021-05-26 17:52:04.6976 200   24.127721ms   172.21.101.17 GET /api/v1/dashboard"}
{"level":"info","ts":"2021-05-26 17:54:38.632065","caller":"middleware/permission.go:24","msg":"admin/api/v1/sysUserListGET"}
{"level":"info","ts":"2021-05-26 17:54:38.634608","caller":"middleware/permission.go:24","msg":"admin/api/v1/deptTreeGET"}
{"level":"info","ts":"2021-05-26 17:54:38.635228","caller":"middleware/logger.go:39","msg":" 2021-05-26 17:54:38.6246 200   10.558163ms   172.21.101.17 GET /api/v1/sysUserList?pageIndex=1&pageSize=10"}
{"level":"info","ts":"2021-05-26 17:54:38.636570","caller":"middleware/logger.go:39","msg":" 2021-05-26 17:54:38.6246 200   11.909602ms   172.21.101.17 GET /api/v1/deptTree"}
{"level":"info","ts":"2021-05-26 17:54:39.628381","caller":"middleware/permission.go:24","msg":"admin/api/v1/dashboardGET"}
{"level":"error","ts":"2021-05-26 17:54:39.642083","caller":"app/return.go:17","msg":"查询处理工单人员排行失败"}

环境：
CentOS 7.6

docker version
Client: Docker Engine - Community
 Version:           19.03.9
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        9d988398e7
 Built:             Fri May 15 00:25:27 2020
 OS/Arch:           linux/amd64
 Experimental:      false

不知道是不是哪里配置的问题，谢谢

**Comment by lanyulei** [comment]
表缺少字段。

**Comment by jiangtaowu** [comment]
@gander001 @lanyulei 你好，请问这个问题解决了么，我用docker部署碰到了和你一样的问题
