### ISSUE TITLE
手动部署 安装后为啥总是不显示验证码呢？

### ISSUE THREAD

**Issue by yidoa** [lanyulei/ferry#205]

**Comment by yidoa** [comment]
前后端程序 都是正常的
![image](https://user-images.githubusercontent.com/87849176/126747263-bab377b8-bc77-40d4-8f65-7e15d9fb52f0.png)

**Comment by yidoa** [comment]
![image](https://user-images.githubusercontent.com/87849176/126747346-d566e0c9-c6a9-46d1-bf1e-13450bddd6ae.png)
手动部署 安装后为啥总是不显示验证码呢

**Comment by huangchanghu** [comment]
看是不是因为请求的是localhost? 我之前好像遇到

**Comment by yidoa** [comment]
config/settings.yml  这个文件配置的具体的IP 
![image](https://user-images.githubusercontent.com/87849176/126754208-09c09b3f-b264-4084-a779-2828689b4da5.png)

.env.production  这个文件 也是配置具体ip：8002

**Comment by lanyulei** [comment]
推荐脚本部署。

**Comment by superabbite1** [comment]
我用脚本部署 也是验证码不显示，我是设置的外网ip:8002
