### ISSUE TITLE
go.mod依赖有问题

### ISSUE THREAD

**Issue by nnjojo** [lanyulei/ferry#207]
执行go get时，github.com/dgrijalva/jwt-go v3.2.1+incompatible提示 unknown revision v3.2.1。
我查了下并没有3.2.1这个版本，只有3.2.0
我改成3.2.0请问会有问题吗

**Comment by 0x01x0** [comment]
Step 4/17 : RUN go mod download
 ---> Running in 2832d1ef28eb
go: github.com/dgrijalva/jwt-go@v3.2.1+incompatible: reading github.com/dgrijalva/jwt-go/go.mod at revision v3.2.1: unknown revision v3.2.1
ERROR: Service 'ferry_backend' failed to build: The command '/bin/sh -c go mod download' returned a non-zero code: 1   

同样出现这个问题

**Comment by lanyulei** [comment]
已修复。
