### ISSUE TITLE
工单模板可否根据条件显示某些字段

### ISSUE THREAD

**Issue by marksmansj** [lanyulei/ferry#223]
例如我建立一个开通防火墙的模板，有的需求是开通所有端口或特定端口，在建立模板时，可否实现如果用户点击“所有端口”后就不再显示输入端口框了，只有用户选择“特定端口”选项时才出现填写输入端口的地方

**Comment by lanyulei** [comment]
现在就支持。
![image](https://user-images.githubusercontent.com/20027531/142020933-365e3559-6409-4a3a-83f5-64b5d300ab9e.png)
