### ISSUE TITLE
x509 certificate signed by unknown authority

### ISSUE THREAD

**Issue by iamkulele** [lanyulei/ferry#224]
请问大家是否有碰到docker部署ferry后，邮件无法发出？
settings.yml配置如下: 
  email:
    alias: Ferry
    host: smtp.exmail.qq.com
    pass: 123456
    port: 465
    user: example@example.com

日志如下：
{"level":"info","ts":"2021-09-15 13:28:38.053748","caller":"email/email.go:43","msg":"x509: certificate signed by unknown authority"}

**Comment by lanyulei** [comment]
此类邮件问题，更多为邮箱服务商的配置文件，根据各自的厂商，百度一下问题，排查即可。
