### ISSUE TITLE
并行网关审批报错(带解决方案)

### ISSUE THREAD

**Issue by upling** [lanyulei/ferry#241]
**bug描述**
并行网关审批报"处理工单失败，interface conversion: interface {} is nil, not []map[string]interface {}"

**问题位置**
并行网关发送邮件的bug: /pkg/server/handle.go 888 行
nil 类型断言 为[]map[string]interface{}报错

**Comment by liouxiao** [comment]
请问解决方案是？

**Comment by upling** [comment]
并行网关发送邮件的bug: /pkg/server/handle.go 888 行
// 发送通知bug修正
if len(noticeList) &gt; 0 {
stateList := make([]interface{}, 0)
if h.updateValue[“state”] == nil {
return
}
for _, v := range h.updateValue[“state”].([]map[string]interface{}) {
stateList = append(stateList, v)
}




李平
好玩又热门


 联系我









&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lanyulei/ferry"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月27日(星期一) 下午4:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lanyulei/ferry] 并行网关审批报错(带解决方案) (Issue #241)





 
请问解决方案是？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
