### ISSUE TITLE
docker-compose up -d 报错

### ISSUE THREAD

**Issue by fcmxmk** [lanyulei/ferry#246]
Building ferry_backend
Step 1/33 : FROM node:14.18-alpine as web
14.18-alpine: Pulling from library/node
97518928ae5f: Pull complete
23182d7a473a: Pull complete
c006eebfdd13: Pull complete
a3c2ac39ae5d: Pull complete
Digest: sha256:7bcf853eeb97a25465cb385b015606c22e926f548cbd117f85b7196df8aa0d29
Status: Downloaded newer image for node:14.18-alpine
 ---> 590973483ea0
Step 2/33 : WORKDIR /opt/workflow
 ---> Running in 468aab59c178
Removing intermediate container 468aab59c178
 ---> 5f8dc7af286c
Step 3/33 : RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories
 ---> Running in 266e65893efa
Removing intermediate container 266e65893efa
 ---> beed1b2c862c
Step 4/33 : RUN apk update &&     apk add --no-cache git &&     rm -rf /var/cache/apk/* /tmp/* /var/tmp/* $HOME/.cache
 ---> Running in 2cc6b2251cec
fetch https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
v3.14.3-71-gffbd3325d6 [https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.14/main]
v3.14.3-73-g89aa18397a [https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.14/community]
OK: 14942 distinct packages available
fetch https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
(1/7) Installing ca-certificates (20191127-r5)
(2/7) Installing brotli-libs (1.0.9-r5)
(3/7) Installing nghttp2-libs (1.43.0-r0)
(4/7) Installing libcurl (7.79.1-r0)
(5/7) Installing expat (2.4.1-r0)
(6/7) Installing pcre2 (10.36-r0)
(7/7) Installing git (2.32.0-r0)
Executing busybox-1.33.1-r6.trigger
Executing ca-certificates-20191127-r5.trigger
OK: 21 MiB in 23 packages
Removing intermediate container 2cc6b2251cec
 ---> 7ca75f97d4f9
Step 5/33 : RUN git clone https://gitee.com/yllan/ferry_web.git
 ---> Running in 58517de10699
Cloning into 'ferry_web'...
Removing intermediate container 58517de10699
 ---> cc707d468fde
Step 6/33 : WORKDIR ferry_web
 ---> Running in 952846e68452
Removing intermediate container 952846e68452
 ---> 7838af0e7157
Step 7/33 : RUN npm install -g cnpm --registry=https://registry.npm.taobao.org
 ---> Running in de2f728d6eab
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/local/bin/cnpm -> /usr/local/lib/node_modules/cnpm/bin/cnpm
+ cnpm@7.1.0
added 851 packages from 974 contributors in 29.837s
Removing intermediate container de2f728d6eab
 ---> c22e25b9b74b
Step 8/33 : RUN cnpm install
 ---> Running in e7d32b5b5578
[tui-editor@1.3.3 › squire-rte@github:sohee-lee7/Squire#b1e0e1031fa18912d233c204cbe7c7fae4a42621] install squire-rte from git squire-rte@github:sohee-lee7/Squire#b1e0e1031fa18912d233c204cbe7c7fae4a42621, may be very slow, please keep patience
[tui-editor@1.3.3 › tui-chart@3.11.3 › raphael@git+https://github.com/nhn/raphael.git#2.2.0-c] install raphael from git raphael@git+https://github.com/nhn/raphael.git#2.2.0-c, may be very slow, please keep patience
[tui-editor@1.3.3 › tui-chart@3.11.3 › raphael@2.2.0-c › eve@git://github.com/adobe-webplatform/eve.git#eef80ed] install eve from git eve@git://github.com/adobe-webplatform/eve.git#eef80ed, may be very slow, please keep patience
✖ Install fail! Error: [tui-editor@1.3.3 › tui-chart@3.11.3 › raphael@2.2.0-c › eve@git://github.com/adobe-webplatform/eve.git#eef80ed] An unknown git error occurred
Error: [tui-editor@1.3.3 › tui-chart@3.11.3 › raphael@2.2.0-c › eve@git://github.com/adobe-webplatform/eve.git#eef80ed] An unknown git error occurred
    at module.exports (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/download/git.js:36:11)
    at async module.exports (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/download/index.js:17:12)
    at async _install (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/install.js:125:16)
    at async install (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/install.js:26:12)
    at async mapper (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/install.js:266:9)
npminstall version: 5.3.1
npminstall args: /usr/local/bin/node /usr/local/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --fix-bug-versions --china --userconfig=/root/.cnpmrc --disturl=https://npmmirror.com/mirrors/node --registry=https://registry.npmmirror.com
ERROR: Service 'ferry_backend' failed to build: The command '/bin/sh -c cnpm install' returned a non-zero code: 1

看着像是因为无法访问 `github.com` 造成的.

**Comment by lanyulei** [comment]
docker-compose 已取消这种部署方式。
