### ISSUE TITLE
模板管理打不开，报错

### ISSUE THREAD

**Issue by moyision** [lanyulei/ferry#269]
**Describe the bug**
非docker部署成功后，模板管理打不开，报错，其他功能正常

**To Reproduce**

1. 菜单选择工单系统
2. 选择工单系统下的 后台管理
3. 点击 模板管理
4. 无法正常打开模板管理，控制台报错

**Expected behavior**
正常打开模板管理页面

**Screenshots**
![image](https://user-images.githubusercontent.com/49543264/178037315-5d6ddf51-418c-434d-b7dc-e54e20bfc85d.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lanyulei** [comment]
done
