### ISSUE TITLE
请问部署文档能否详细一点？

### ISSUE THREAD

**Issue by nanqic** [lanyulei/ferry#283]
**Describe the bug**

**To Reproduce**
1. 拉取了docker镜像
2. 修改了dev配置mysql
3. 创建了needinit文件
4. 修改docker命令为 docker run -itd --name ferry -v /home/hj/apps/ferry/config -p 1080:8002 lanyulei/ferry:1.0.1
5. 启动过程
``` 
 docker images ls -a
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE
➜  config git:(master) ✗ docker image ls -a
REPOSITORY       TAG       IMAGE ID       CREATED         SIZE
lanyulei/ferry   1.0.1     87a5ceba8bce   10 months ago   146MB
➜  config git:(master) ✗ docker run 87a
```

**Expected behavior**
成功运行

**Desktop (please complete the following information):**
 - OS: CentOS 7

**Additional context**
得到报错：
start init
{"level":"fatal","ts":"2022-09-22 03:47:00.458021","caller":"database/mysql.go:35","msg":"mysql connect error dial tcp 192.168.31.94:3306: i/o timeout"}

我不知道`192.168.31.94`这个ip是在哪里读取到的，请问配置可以详细一些吗

**Comment by micro-stone** [comment]
我也出现这个问题，配置文档里相关参数和地址都改过了

**Comment by yaodunlin** [comment]
![image](https://github.com/lanyulei/ferry/assets/37436336/22cba013-7281-4672-9f3a-8dc7e504be3e)

**Comment by yaodunlin** [comment]
我的也是一样
![Uploading image.png…]()

**Comment by yaodunlin** [comment]
![image](https://github.com/lanyulei/ferry/assets/37436336/85dd1471-0019-4885-a313-d8981d2f3f77)

**Comment by yaodunlin** [comment]
我的也是一样
