### ISSUE TITLE
docker部署后，附件上传失败，有报错

### ISSUE THREAD

**Issue by xgxshtc** [lanyulei/ferry#309]
Error: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL at a.th (http://order.xxxx.tech/static/web/js/chunk-elementUI.297346c4.js:1:432026) at a.post (http://order.xxxx.tech/static/web/js/chunk-elementUI.297346c4.js:1:435395) at a.upload (http://order.xxxx.tech/static/web/js/chunk-elementUI.297346c4.js:1:434557) at http://order.xxxx.tech/static/web/js/chunk-elementUI.297346c4.js:1:434450 at Array.forEach (<anonymous>) at a.uploadFiles (http://order.xxxx.tech/static/web/js/chunk-elementUI.297346c4.js:1:434400) at a.handleChange (http://order.xxxx.tech/static/web/js/chunk-elementUI.297346c4.js:1:434158) at re (http://order.xxxx.tech/static/web/js/chunk-libs.3497728e.js:11:11674) at HTMLInputElement.n (http://order.xxxx.tech/static/web/js/chunk-libs.3497728e.js:11:13494) at Qi.o._wrapper (http://order.xxxx.tech/static/web/js/chunk-libs.3497728e.js:11:52151)

**Comment by Gilgamesh0220** [comment]
遇到了同样的问题，大佬能指导下如何修改代码嘛
