### ISSUE TITLE
报告本系统的一个严重安全漏洞

### ISSUE THREAD

**Issue by prship** [lanyulei/ferry#328]
漏洞1：jwt空密钥
按照说明文档，应当使用如下命令运行程序
./ferry server -c=config/settings.yml
理论上，程序应当加载settings.yml中的jwt-secret。
然而，程序实际并不会使用settings.yml中的jwt-secret。
从文件router\router.go追踪登录接口“/post”
![图片](https://github.com/user-attachments/assets/1f13797c-db48-4d52-9547-714ac4f90d5c)
跟进LoginHandler
进入文件pkg\jwtauth\jwtauth.go，
![图片](https://github.com/user-attachments/assets/5fabe222-b67d-4503-a794-23fda572709d)
跟进signedString
![图片](https://github.com/user-attachments/assets/b0bf4900-681f-4a9c-8c16-32ac4373e5a4)
由于默认使用的是对称加密，跟进mw.Key，发现是空字符
![图片](https://github.com/user-attachments/assets/1446958d-b310-45e6-9c90-4facaf3c1400)
实际搭建环境，验证确实是使用的空密钥
![图片](https://github.com/user-attachments/assets/c224a55a-60cf-4faa-82f0-a88d57085efc)
![图片](https://github.com/user-attachments/assets/ebdf9cb2-39be-460a-a1a7-f6feab971b5a)

这将导致任何人都可以使用已知的payload和空secret伪造一个合法的jwt来登录、接管系统。

**Comment by prship** [comment]
闹笑话了，家人们，这个漏洞是存在的，但我是代码菜鸡，代码分析部分可能有点问题，具体详情请以作者大大分析的为准。
我又看了下，可能是这样的。
请参考这里：文件middleware\auth.go，跟进JwtSecret
![图片](https://github.com/user-attachments/assets/85903c85-4647-486b-b77c-e6ac327aae76)
跳转到了tools\config\application.go，这里JwtSecret被赋值为cfg.GetString("jwtSecret")，跟进InitApplication()
![图片](https://github.com/user-attachments/assets/cb03bd1e-8b26-41bc-bc6d-8231754b898c)
跳转到了tools\config\config.go
![图片](https://github.com/user-attachments/assets/437931a4-1197-410d-9361-44df3dd45820)
可以发现传入InitApplication()的cfgApplication是settings.application，但config\settings.yml文件中application部分并没有jwtSecret
![图片](https://github.com/user-attachments/assets/b6e47049-5b03-4548-8317-c3b6b62a3fbc)

**Comment by lanyulei** [comment]
已修复。
