### ISSUE TITLE
Feature：模板基础字段中提供密码插件

### ISSUE THREAD

**Issue by gaoyangzhang** [lanyulei/ferry#37]
## 背景

- 在工单的实际使用过程中，工单中可能会有部分字段属于个人私有信息，不应当对外暴露

## 思路

1. 在工单的模板管理->编辑模板->基础字段中增加密码插件
2. 在提交申请后，工单的查询和审批界面不应当显示具体的私有信息
3. 在Python或者Shell后端执行的脚本能够获取到具体的私有信息

**Comment by lanyulei** [comment]
已经在单行输出中添加 密码 类型。
