### ISSUE TITLE
Feature：工单模板向Python脚本传参使用Dict格式

### ISSUE THREAD

**Issue by gaoyangzhang** [lanyulei/ferry#38]
## 背景

- 目前模板向Python模板的传参使用的是list格式，Python通过`app(*args)`方法接受参数，这样会导致代码维护困难，需要严格按照顺序接受参数。如果模板发生修改，在更新相应脚本的过程中容易出错。

## 思路
- 模板管理下的编辑模板中的预览提供获取数据功能，是以`{"字段名称":参数值}`的json格式返回
- 模板中提供了字段标示的修改功能

考虑将Python的`app(*args)`变为`app(**kwargs)`。在设计模板的时候修改字段标示的值。在编写`app`函数的时候，可以直接通过字段标示设置的变量名获取对应的模板中的参数值，方便不容易出错

**Comment by lanyulei** [comment]
Python任务脚本的接收参数，已经设置配置为json形式，但是需要脚本里面添加接收的代码。例如Python的 sys.args[1]。
