### ISSUE TITLE
执行任务脚本问题

### ISSUE THREAD

**Issue by shundonglin** [lanyulei/ferry#44]
1、执行python脚本报错，shell 脚本执行也不需要 -c 参数。修改为下面代码正常运行
task.go :
func executeTaskBase(classify string, scriptPath string) {
	
	command := exec.Command("/bin/bash", scriptPath) //初始化Cmd
	if classify == "python" {
		command = exec.Command("python", scriptPath) //初始化Cmd
	}
}

2、流程在某个节点处理时调用任务的时候，应该需要获取任务执行状态，如果失败需要手动处理完再进去下个环节

**Comment by lanyulei** [comment]
done
