### ISSUE TITLE
图片上传有问题

### ISSUE THREAD

**Issue by alexlinbin** [lanyulei/ferry#46]
![image](https://user-images.githubusercontent.com/33760053/93285354-3a03ab80-f807-11ea-86a2-9060dc0fb7cc.png)
![image](https://user-images.githubusercontent.com/33760053/93285374-44be4080-f807-11ea-9e0e-190dcec06e11.png)
1.图片上传有问题
2.创建新的普通用户后，所有用户图片都不能上传。都是以上截图的报错

**Comment by lanyulei** [comment]
已修复。
