### ISSUE TITLE
是否可以实现根据不同业务模块分发到不同组

### ISSUE THREAD

**Issue by wiliiwin** [lanyulei/ferry#55]
![image](https://user-images.githubusercontent.com/20533148/94355606-fbe47280-00b7-11eb-9865-93d560f9b337.png)
是否可以添加一个根据发起人选择的不同模块分发工单到对应的组里面，组里面的人员都可以看到这个工单，并且不需要进行审批

**Comment by lanyulei** [comment]
新建工单已支持排他网关。
