### ISSUE TITLE
搜索方面的建议-和其他一些bug的提交

### ISSUE THREAD

**Issue by th815** [lanyulei/ferry#62]
# 级联选择器有问题

级联选择器没有设置列表项的地方 

![image-20200929150358499](https://gitee.com/th815/images/raw/master/blog/image-20200929150358499.png)

![image-20200929150232023](https://gitee.com/th815/images/raw/master/blog/image-20200929150232023.png)

**紧急需求**

# 所有工单列表支持模糊搜索

希望添加所有工单列表支持模糊搜索和自定义字段搜索包括级联选择项里面的字段进行筛选查询

类似于如图这种

![image-20200929150305639](https://gitee.com/th815/images/raw/master/blog/image-20200929150305639.png)

![image-20200929150008968](https://gitee.com/th815/images/raw/master/blog/image-20200929150008968.png)

 **次级需求**

# 首页图表展现页面能自定义字段展示

![image-20200929164428224](https://gitee.com/th815/images/raw/master/blog/image-20200929164428224.png)

现在首页显示的是用户提交的工单排名，在实际过程中，这个并不是很需要的，能否自定义字段展示比如某个产品的工单数量。

**次级需求**

# 所有工单展示页列表项支持自定义字段显示

希望添加工单展示页列表项除了系统定义的id/标题/当前状态/当前处理人/优先级/创建时间/操作/ 等  还能支持自定义字段展示并可以排序保存。或者提供可定制页面保存。

![image-20200929150059817](https://gitee.com/th815/images/raw/master/blog/image-20200929150059817.png)

![image-20200929150134531](https://gitee.com/th815/images/raw/master/blog/image-20200929150134531.png)

**次次次级需求**

**Comment by lanyulei** [comment]
级连选择器已经可以配置静态选项。

**Comment by th815** [comment]
![image](https://user-images.githubusercontent.com/38848740/96977252-68378200-154f-11eb-9d59-665517c5c9a8.png)
![image](https://user-images.githubusercontent.com/38848740/96977273-6e2d6300-154f-11eb-98a3-5d49627a9fe8.png)
所有的列表可以增加排序么，全局排序最好，没有类似的事件就添加个当页排序也中[表情]

**Comment by th815** [comment]
![image](https://user-images.githubusercontent.com/38848740/96978461-f7916500-1550-11eb-898a-e38109b505ac.png)
![image](https://user-images.githubusercontent.com/38848740/96978582-17c12400-1551-11eb-8f94-7239d7294b25.png)

计数器在模板内做限制情况下会出现匹配不到的情况
