### ISSUE TITLE
执行脚本出错

### ISSUE THREAD

**Issue by zyfjfj** [lanyulei/ferry#64]
执行脚本时报错怎么解决？
{"level":"error","ts":"2020-10-07 21:58:50.035036","caller":"worker/tasks.go:19","msg":"task exec failed，fork/exec ./static/scripts/echo_test-4171bc7f4a05-admin.sh: permission deied"}。
谢谢！

**Comment by lanyulei** [comment]
权限不足，检查一下程序启动用户，是否有执行此脚本的权限。
