### ISSUE TITLE
建议线上部署时增加前端免nginx的部署方式

### ISSUE THREAD

**Issue by flybird119** [lanyulei/ferry#72]
目前线上部署的时候，前端代码需要通过部署nginx来代理，这个会增加部署难度和后期线上出问题的可能性。 
希望能增加一种ferry+前端代码的直接部署方式，即通过修改gin来实现前端静态资源的直接访问。

**Comment by octvian** [comment]
正如昨天的讨论，建议增加ferry（golang后台）+前端代码打包的方式运行的方式，方便后端用户开发使用

**Comment by lanyulei** [comment]
已添加，更新最新的前后端即可。
文档： https://www.fdevops.com/docs/ferry-tutorial-document/8931-2
