### ISSUE TITLE
流程不同逻辑流程绑定不同模板存在必填属性会报错。

### ISSUE THREAD

**Issue by th815** [lanyulei/ferry#76]
在流程绑定多个模板的时候隐藏的模板里面有必须必填属性，隐藏了的话就过不去流程，设置只读不隐藏的话在申请工单的时候，实际上还是可以写的。
![image](https://user-images.githubusercontent.com/38848740/96833048-5af89580-1472-11eb-80e6-b43072e9ad15.png)
--------------------
![image](https://user-images.githubusercontent.com/38848740/96833253-b460c480-1472-11eb-844e-62c596ec1ad9.png)
![image](https://user-images.githubusercontent.com/38848740/96833268-b88ce200-1472-11eb-9352-06168d4e1290.png)
设定了最小值 还是可以选择到负数

**Comment by lanyulei** [comment]
已修复。
