### ISSUE TITLE
文件上传Bug

### ISSUE THREAD

**Issue by hucaloof** [lanyulei/ferry#79]
模板中增加文件上传，但是文件上传后找不到上传的文件，接口使用的还是图片上传地址
![image](https://user-images.githubusercontent.com/10459360/97407997-75c97f00-1936-11eb-9178-00b350eca5ad.png)

**Comment by lanyulei** [comment]
需要配置图片上传地址，请参考如下。

https://www.fdevops.com/docs/ferry-tutorial-document/install

![image](https://user-images.githubusercontent.com/20027531/98087119-a1aaae80-1eba-11eb-8d06-bb21408ad0cb.png)
