### ISSUE TITLE
安装完成后，配置好流程试用创建新工单时提交报错

### ISSUE THREAD

**Issue by silencefent** [lanyulei/ferry#80]
/api/v1/work-order/create

192.168.100.223:56151是我路由器的地址，不知道为什么会连到这个端口和ip

2020/11/02 15:58:52 http: panic serving 192.168.100.223:56151: interface conversion: interface {} is nil, not string
goroutine 59 [running]:
net/http.(*conn).serve.func1(0xc002fdfb80)
	/usr/local/go/src/net/http/server.go:1801 +0x147
panic(0x14b3e00, 0xc000c98750)
	/usr/local/go/src/runtime/panic.go:975 +0x47a
ferry/middleware.CustomError.func1(0xc002ff89c0)
	/home/www/ferry/middleware/customerror.go:44 +0x5d3
panic(0x14b3e00, 0xc000c98750)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
ferry/pkg/service.CreateWorkOrder(0xc002ff89c0, 0x140bec0, 0x192d0e0)
	/home/www/ferry/pkg/service/createWorkOrder.go:106 +0x3f5f
ferry/apis/process.AddWorkOrder(0xc002ff89c0)
	/home/www/ferry/apis/process/workOrder.go:60 +0x6a
github.com/gin-gonic/gin.(*Context).Next(0xc002ff89c0)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 +0x3b
ferry/middleware.AuthCheckRole.func1(0xc002ff89c0)
	/home/www/ferry/middleware/permission.go:28 +0x67b
github.com/gin-gonic/gin.(*Context).Next(0xc002ff89c0)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 +0x3b
ferry/pkg/jwtauth.(*GinJWTMiddleware).middlewareImpl(0xc0006c2900, 0xc002ff89c0)
	/home/www/ferry/pkg/jwtauth/jwtauth.go:406 +0x2de
ferry/pkg/jwtauth.(*GinJWTMiddleware).MiddlewareFunc.func1(0xc002ff89c0)
	/home/www/ferry/pkg/jwtauth/jwtauth.go:369 +0x34
github.com/gin-gonic/gin.(*Context).Next(0xc002ff89c0)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 +0x3b
ferry/middleware.AuthCheckRole.func1(0xc002ff89c0)
	/home/www/ferry/middleware/permission.go:28 +0x67b
github.com/gin-gonic/gin.(*Context).Next(0xc002ff89c0)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 +0x3b
ferry/pkg/jwtauth.(*GinJWTMiddleware).middlewareImpl(0xc0006c2900, 0xc002ff89c0)
	/home/www/ferry/pkg/jwtauth/jwtauth.go:406 +0x2de
ferry/pkg/jwtauth.(*GinJWTMiddleware).MiddlewareFunc.func1(0xc002ff89c0)
	/home/www/ferry/pkg/jwtauth/jwtauth.go:369 +0x34
github.com/gin-gonic/gin.(*Context).Next(0xc002ff89c0)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 +0x3b
ferry/middleware.AuthCheckRole.func1(0xc002ff89c0)
	/home/www/ferry/middleware/permission.go:28 +0x67b
github.com/gin-gonic/gin.(*Context).Next(0xc002ff89c0)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 +0x3b
ferry/pkg/jwtauth.(*GinJWTMiddleware).middlewareImpl(0xc0006c2900, 0xc002ff89c0)
	/home/www/ferry/pkg/jwtauth/jwtauth.go:406 +0x2de
ferry/pkg/jwtauth.(*GinJWTMiddleware).MiddlewareFunc.func1(0xc002ff89c0)
	/home/www/ferry/pkg/jwtauth/jwtauth.go:369 +0x34
github.com/gin-gonic/gin.(*Context).Next(0xc002ff89c0)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 +0x3b
ferry/middleware.RequestId.func1(0xc002ff89c0)
	/home/www/ferry/middleware/requestid.go:24 +0x1eb
github.com/gin-gonic/gin.(*Context).Next(0xc002ff89c0)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 +0x3b
ferry/middleware.Options(0xc002ff89c0)
	/home/www/ferry/middleware/header.go:23 +0x3d
github.com/gin-gonic/gin.(*Context).Next(0xc002ff89c0)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 +0x3b
ferry/middleware.NoCache(0xc002ff89c0)
	/home/www/ferry/middleware/header.go:15 +0x16a
github.com/gin-gonic/gin.(*Context).Next(0xc002ff89c0)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 +0x3b
ferry/middleware.CustomError(0xc002ff89c0)
	/home/www/ferry/middleware/customerror.go:48 +0x4e
github.com/gin-gonic/gin.(*Context).Next(0xc002ff89c0)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 +0x3b
ferry/middleware.LoggerToFile.func1(0xc002ff89c0)
	/home/www/ferry/middleware/logger.go:18 +0x6b
github.com/gin-gonic/gin.(*Context).Next(0xc002ff89c0)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147 +0x3b
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc000160280, 0xc002ff89c0)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/gin.go:403 +0x685
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc000160280, 0x1979980, 0xc003686700, 0xc000404100)
	/root/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/gin.go:364 +0x14d
net/http.serverHandler.ServeHTTP(0xc0002582a0, 0x1979980, 0xc003686700, 0xc000404100)
	/usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc002fdfb80, 0x197ebc0, 0xc0036801c0)
	/usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2969 +0x36c

**Comment by lanyulei** [comment]
你在前端编译的时候，是不是用的这个地址呢。？

**Comment by silencefent** [comment]
今天将/api/v1/work-order/create post提交的参数里,stete:{}这项的内容全部删掉,只保留基本的字段,在postman里面提交成功了,是不是github上的版本对state这个json解析有问题

**Comment by lanyulei** [comment]
方便提供一下，state的数据吗？因为我这边测试，是没问题的。

**Comment by silencefent** [comment]
{"title":"111","priority":1,"process":3,"classify":2,"state":[{"id":"exclusiveGateway1604027040028","label":"是否经由单位登记"}],"source":"start1604026783998","source_state":"开始","process_method":"","tpls":{"form_structure":[{"list":[{"key":"1604026599000_85324","icon":"icon-input","name":"项目名称","type":"input","model":"input_1604026599000_85324","rules":[{"type":"string","message":"项目名称格式不正确"}],"options":{"width":"100%","pattern":"","dataType":"string","disabled":false,"required":false,"labelWidth":100,"remoteFunc":"func_1604026599000_85324","placeholder":"","defaultValue":"","showPassword":false,"labelWidthStatus":true,"labelWidthDisabled":false}},{"key":"1604026610000_71640","icon":"icon-input","name":"项目编号","type":"input","model":"input_1604026610000_71640","rules":[{"type":"string","message":"项目编号格式不正确"}],"options":{"width":"100%","pattern":"","dataType":"string","disabled":false,"required":false,"labelWidth":100,"remoteFunc":"func_1604026610000_71640","placeholder":"","defaultValue":"","showPassword":false,"labelWidthStatus":true,"labelWidthDisabled":false}},{"key":"1604026628000_11011","icon":"icon-input","name":"送审金额","type":"input","model":"input_1604026628000_11011","rules":[{"type":"string","message":"送审金额格式不正确"}],"options":{"width":"100%","pattern":"","dataType":"string","disabled":false,"required":false,"labelWidth":100,"remoteFunc":"func_1604026628000_11011","placeholder":"","defaultValue":"","showPassword":false,"labelWidthStatus":true,"labelWidthDisabled":false}},{"key":"1604026644000_99215","icon":"icon-select","name":"送审人","type":"select","model":"select_1604026644000_99215","rules":[],"options":{"props":{"label":"label","value":"value"},"width":"20%","remote":false,"options":[{"value":"小李"},{"value":"Option 2"},{"value":"Option 3"}],"disabled":false,"multiple":false,"required":false,"clearable":false,"showLabel":false,"filterable":false,"labelWidth":100,"remoteFunc":"func_1604026644000_99215","placeholder":"","defaultValue":"小李","remoteOptions":[],"labelWidthStatus":true,"labelWidthDisabled":true}},{"key":"1604026711000_87518","icon":"icon-time","name":"开始时间","type":"time","model":"time_1604026711000_87518","rules":[],"options":{"width":"","format":"HH:mm:ss","isRange":false,"disabled":false,"editable":true,"readonly":false,"required":false,"clearable":true,"labelWidth":100,"remoteFunc":"func_1604026711000_87518","placeholder":"","arrowControl":true,"defaultValue":"","endPlaceholder":"","labelWidthStatus":true,"startPlaceholder":"","labelWidthDisabled":false}},{"key":"1604026730000_24316","icon":"icon-diy-com-textarea","name":"备注","type":"textarea","model":"textarea_1604026730000_24316","rules":[],"options":{"width":"100%","pattern":"","disabled":false,"required":false,"labelWidth":100,"remoteFunc":"func_1604026730000_24316","placeholder":"","defaultValue":"","labelWidthStatus":true,"labelWidthDisabled":false}},{"key":"1604026737000_72570","icon":"icon-wenjianshangchuan","name":"送审资料","type":"file","model":"file_1604026737000_72570","rules":[],"options":{"tip":"","token":"","width":"","action":"https://jsonplaceholder.typicode.com/photos/","domain":"http://pfp81ptt6.bkt.clouddn.com/","length":9,"headers":{},"disabled":false,"tokenFunc":"funcGetToken","labelWidth":100,"remoteFunc":"func_1604026737000_72570","defaultValue":[],"labelWidthStatus":true,"labelWidthDisabled":false}}],"config":{"size":"small","labelWidth":100,"customClass":"","labelPosition":"right"},"id":6}],"form_data":[{"input_1604026599000_85324":"111111111","input_1604026610000_71640":"222222222","input_1604026628000_11011":"333333333333","select_1604026644000_99215":"小李","time_1604026711000_87518":"17:00:59","textarea_1604026730000_24316":"444444444","file_1604026737000_72570":[]}]},"tasks":["echo_test-4171bc7f4a05-admin.sh"]}

**Comment by lanyulei** [comment]
我这边看，json是能解析的，方便的话，加qq群吧，方便解决问题。

**Comment by silencefent** [comment]
按您的说法,我先更新一下软件的版本试试

**Comment by lanyulei** [comment]
我这边没有复现类似的问题呢，先把这个issuse关了，还有相关的问题的话，可以加群详聊。

**Comment by czxin788** [comment]
我也遇到了这个问题
出现我路由器的地址
