### ISSUE TITLE
点击我的待办，不能获取到内容，只能重新登录

### ISSUE THREAD

**Issue by hanfeng712** [lanyulei/ferry#83]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lanyulei** [comment]
额，可以更详细的描述一下吗？

**Comment by lanyulei** [comment]
我这边测试是没问题的，请再次确认吧。
