### ISSUE TITLE
请问“并行网关”流程该怎么使用呢？我摸索不出来

### ISSUE THREAD

**Issue by vanplus** [lanyulei/ferry#94]
可否在 [fdevops 演示](http://fdevops.com:8001/#/process/admin/process-manager) 中提供一个例子呢？

**Comment by lanyulei** [comment]
![image](https://user-images.githubusercontent.com/20027531/98625660-fa5ec900-234a-11eb-9210-900ecbb7a2d4.png)

已经添加。

**Comment by vanplus** [comment]
谢谢！验证使用无误。
